# Generated by Django 5.2.8 on 2026-09-28 16:47

import apps.media_center.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Gallery categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Uploaded video"),
                            ("youtube", "YouTube video"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="gallery/images/")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="MP4, WebM or OGG; maximum 80 MB.",
                        upload_to="gallery/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "ogg"]
                            ),
                            apps.media_center.models.validate_media_size,
                        ],
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, help_text="Paste a YouTube video or Shorts URL."
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended for uploaded videos. YouTube thumbnails load automatically.",
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=500)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="media_center.gallerycategory",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-event_date", "-created_at"),
            },
        ),
    ]
