# Generated by Django 5.2.8 on 2026-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(max_length=100)),
                (
                    "enquiry_type",
                    models.CharField(
                        choices=[
                            ("product", "Product enquiry"),
                            ("dealer", "Dealership enquiry"),
                            ("bulk", "Bulk / project requirement"),
                            ("support", "Customer support"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact enquiry",
                "verbose_name_plural": "Contact enquiries",
                "ordering": ("-created_at",),
            },
        ),
    ]
