# Generated by Django 5.2.8 on 2026-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactenquiry",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
