# Generated by Django 5.2.8 on 2026-09-28 12:46

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(upload_to="hero_slides/")),
                ("cta_1_label", models.CharField(blank=True, max_length=50)),
                ("cta_1_url", models.CharField(blank=True, max_length=300)),
                ("cta_2_label", models.CharField(blank=True, max_length=50)),
                ("cta_2_url", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Slide",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About Us"),
                            ("leadership", "Board of Directors / Leadership"),
                            ("products", "Products"),
                            ("manufacturing_partners", "Manufacturing Partners"),
                            ("distribution_network", "Distribution Network"),
                            ("star_dealer_program", "Star Dealer Program"),
                            ("star_engineer_program", "Star Engineer Program"),
                            (
                                "star_mason_contractor_scheme",
                                "Star Mason & Contractor Scheme",
                            ),
                            ("rewards_recognition", "Rewards & Recognition"),
                            ("quality_assurance", "Quality Assurance"),
                            ("safety_sustainability", "Safety & Sustainability"),
                            ("csr", "Corporate Responsibility (CSR)"),
                            ("roadmap", "Future Expansion / Roadmap"),
                            ("gallery", "Gallery"),
                            ("careers", "Careers"),
                            ("blog", "Blog / News"),
                            ("faq", "FAQ"),
                            ("contact", "Contact Us"),
                            ("privacy_terms", "Privacy Policy & Terms"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "hero_bg_image",
                    models.ImageField(blank=True, null=True, upload_to="page_heroes/"),
                ),
                (
                    "hero_overlay_opacity",
                    models.PositiveIntegerField(default=50, help_text="0-100"),
                ),
                ("hero_cta_label", models.CharField(blank=True, max_length=50)),
                ("hero_cta_url", models.CharField(blank=True, max_length=300)),
                ("hero_cta_2_label", models.CharField(blank=True, max_length=50)),
                ("hero_cta_2_url", models.CharField(blank=True, max_length=300)),
                ("show_breadcrumb", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "share_image",
                    models.ImageField(blank=True, null=True, upload_to="page_shares/"),
                ),
                ("noindex", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="SISTECH Cement & TMT Pvt. Ltd.", max_length=200
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "tagline",
                    models.CharField(
                        default="Solid Foundation, Strong Future.", max_length=200
                    ),
                ),
                (
                    "logo_header",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "logo_footer",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "default_share_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("phone_primary", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="With country code, digits only, e.g. 919876543210",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_message",
                    models.CharField(
                        blank=True,
                        default="Hello, I would like to know more about SISTECH products.",
                        max_length=300,
                    ),
                ),
                ("email_contact", models.EmailField(blank=True, max_length=254)),
                ("email_career", models.EmailField(blank=True, max_length=254)),
                ("email_support", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "map_lat",
                    models.DecimalField(
                        decimal_places=6, default=22.7196, max_digits=9
                    ),
                ),
                (
                    "map_lng",
                    models.DecimalField(
                        decimal_places=6, default=75.8577, max_digits=9
                    ),
                ),
                ("map_zoom", models.PositiveIntegerField(default=14)),
                ("business_hours", models.CharField(blank=True, max_length=200)),
                ("gst_number", models.CharField(blank=True, max_length=20)),
                ("cin_number", models.CharField(blank=True, max_length=30)),
                ("social_facebook", models.URLField(blank=True)),
                ("social_instagram", models.URLField(blank=True)),
                ("social_linkedin", models.URLField(blank=True)),
                ("social_youtube", models.URLField(blank=True)),
                ("social_x", models.URLField(blank=True)),
                ("social_indiamart", models.URLField(blank=True)),
                ("footer_about", models.TextField(blank=True)),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        default="© SISTECH Cement & TMT Pvt. Ltd. All rights reserved.",
                        max_length=200,
                    ),
                ),
                (
                    "ga_id",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "head_scripts",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only. Raw HTML/JS injected before </head>.",
                    ),
                ),
                (
                    "footer_scripts",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only. Raw HTML/JS injected before </body>.",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="We're performing scheduled maintenance. Please check back soon.",
                    ),
                ),
                (
                    "robots_txt",
                    models.TextField(blank=True, default="User-agent: *\nAllow: /\n"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_primary", models.CharField(default="#14337F", max_length=7)),
                (
                    "color_primary_dark",
                    models.CharField(default="#0C2259", max_length=7),
                ),
                ("color_accent", models.CharField(default="#F2B705", max_length=7)),
                ("color_text", models.CharField(default="#1F2937", max_length=7)),
                ("color_muted", models.CharField(default="#6B7280", max_length=7)),
                ("color_background", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "color_alt_background",
                    models.CharField(default="#F5F7FA", max_length=7),
                ),
                ("color_border", models.CharField(default="#E5E7EB", max_length=7)),
                ("color_header_bg", models.CharField(default="#FFFFFF", max_length=7)),
                ("color_footer_bg", models.CharField(default="#0C2259", max_length=7)),
                (
                    "heading_font",
                    models.CharField(
                        choices=[
                            ("system", "System default"),
                            ("poppins", "Poppins"),
                            ("montserrat", "Montserrat"),
                            ("roboto", "Roboto"),
                            ("inter", "Inter"),
                            ("open_sans", "Open Sans"),
                            ("barlow", "Barlow"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        choices=[
                            ("system", "System default"),
                            ("poppins", "Poppins"),
                            ("montserrat", "Montserrat"),
                            ("roboto", "Roboto"),
                            ("inter", "Inter"),
                            ("open_sans", "Open Sans"),
                            ("barlow", "Barlow"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "base_font_size",
                    models.PositiveIntegerField(
                        default=16, help_text="Base font size in pixels."
                    ),
                ),
                (
                    "border_radius",
                    models.CharField(
                        choices=[
                            ("sharp", "Sharp"),
                            ("soft", "Soft"),
                            ("round", "Round"),
                        ],
                        default="soft",
                        max_length=10,
                    ),
                ),
                (
                    "container_width",
                    models.PositiveIntegerField(
                        default=1200, help_text="Max content width in pixels."
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("solid", "Solid"),
                            ("outline", "Outline"),
                            ("pill", "Pill"),
                        ],
                        default="solid",
                        max_length=10,
                    ),
                ),
                ("sticky_header", models.BooleanField(default=True)),
                ("top_bar_enabled", models.BooleanField(default=True)),
                ("whatsapp_button_enabled", models.BooleanField(default=True)),
                ("back_to_top_enabled", models.BooleanField(default=True)),
                ("scroll_animations_enabled", models.BooleanField(default=True)),
                ("dark_footer", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Theme Settings",
                "verbose_name_plural": "Theme Settings",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Used if no page is linked below.",
                        max_length=300,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("new_tab", models.BooleanField(default=False)),
                ("show_in_header", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_button",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this item as a button, e.g. Become a Dealer.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="core.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("richtext", "Rich text"),
                            ("image_text", "Image + text"),
                            ("feature_cards", "Feature cards"),
                            ("stats", "Stats / counters"),
                            ("timeline", "Timeline"),
                            ("steps", "Steps / process"),
                            ("faq_accordion", "FAQ accordion"),
                            ("gallery_strip", "Gallery strip"),
                            ("cta_band", "CTA band"),
                            ("testimonial", "Testimonial / quote"),
                            ("downloads", "Downloads list"),
                            ("map_embed", "Embedded map"),
                            ("custom_html", "Custom HTML (staff-only)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("heading", models.CharField(blank=True, max_length=200)),
                ("subheading", models.CharField(blank=True, max_length=300)),
                (
                    "background_style",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("alt", "Alt background"),
                            ("navy", "Navy"),
                            ("gold", "Gold"),
                            ("image", "Image"),
                        ],
                        default="white",
                        max_length=10,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="section_backgrounds/"
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "padding_size",
                    models.CharField(
                        choices=[("sm", "Small"), ("md", "Medium"), ("lg", "Large")],
                        default="md",
                        max_length=5,
                    ),
                ),
                ("richtext_body", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "image_text_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="section_images/"
                    ),
                ),
                (
                    "image_text_position",
                    models.CharField(
                        choices=[("left", "Image left"), ("right", "Image right")],
                        default="left",
                        max_length=5,
                    ),
                ),
                (
                    "image_text_body",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True),
                ),
                ("cta_band_button_label", models.CharField(blank=True, max_length=50)),
                ("cta_band_button_url", models.CharField(blank=True, max_length=300)),
                ("testimonial_quote", models.TextField(blank=True)),
                ("testimonial_author", models.CharField(blank=True, max_length=150)),
                ("testimonial_role", models.CharField(blank=True, max_length=150)),
                (
                    "map_embed_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "map_embed_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("map_embed_zoom", models.PositiveIntegerField(default=14)),
                (
                    "custom_html",
                    models.TextField(
                        blank=True, help_text="Staff-only. Rendered unescaped."
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Section",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="section_downloads/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionFAQLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "faq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faq.faqitem"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_links",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionFeatureCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon keyword/class name.", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("text", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_cards",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="section_gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=30)),
                ("suffix", models.CharField(blank=True, max_length=10)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionTimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_or_label", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="core.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
