# Generated by Django 5.2.8 on 2026-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themesettings",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("system", "System default"),
                    ("poppins", "Poppins"),
                    ("montserrat", "Montserrat"),
                    ("roboto", "Roboto"),
                    ("inter", "Inter"),
                    ("open_sans", "Open Sans"),
                    ("barlow", "Barlow"),
                ],
                default="poppins",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="heading_font",
            field=models.CharField(
                choices=[
                    ("system", "System default"),
                    ("poppins", "Poppins"),
                    ("montserrat", "Montserrat"),
                    ("roboto", "Roboto"),
                    ("inter", "Inter"),
                    ("open_sans", "Open Sans"),
                    ("barlow", "Barlow"),
                ],
                default="poppins",
                max_length=20,
            ),
        ),
    ]
