# Generated by Django 5.2.8 on 2026-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_themesettings_body_font_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional short text shown under this link inside a dropdown panel.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="footer_column",
            field=models.CharField(
                choices=[
                    ("none", "Not in footer"),
                    ("1", "Footer column 1"),
                    ("2", "Footer column 2"),
                    ("3", "Footer column 3"),
                ],
                default="none",
                help_text="Which footer column this link appears in (independent of 'show in footer').",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="apple_touch_icon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="credit_text",
            field=models.CharField(
                blank=True, default="Website by The Webfix", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="credit_url",
            field=models.URLField(blank=True, default="https://thewebfix.in"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_col1_title",
            field=models.CharField(blank=True, default="Company", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_col2_title",
            field=models.CharField(
                blank=True, default="Products & Programs", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_col3_title",
            field=models.CharField(blank=True, default="Support", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_header_compact",
            field=models.ImageField(
                blank=True,
                help_text="Logo without the tagline line, used when the header is scrolled/collapsed and on mobile.",
                null=True,
                upload_to="site/",
            ),
        ),
    ]
