# Generated by Django 5.2.8 on 2026-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_menuitem_description_menuitem_footer_column_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="credit_text",
            field=models.CharField(
                blank=True, default="Designed & Developed by The Webfix", max_length=100
            ),
        ),
    ]
