# Generated by Django 5.2.8 on 2026-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sitesettings_credit_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_col3_title",
            field=models.CharField(blank=True, default="Contact", max_length=50),
        ),
    ]
