# Generated by Django 5.2.8 on 2026-09-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_sitesettings_footer_col3_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="credit_prefix_text",
            field=models.CharField(
                blank=True,
                default="Designed & Developed by",
                help_text="Plain, non-clickable text shown before the credit link, e.g. 'Designed & Developed by'.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="credit_text",
            field=models.CharField(
                blank=True,
                default="The Webfix",
                help_text="Only this part is a clickable link, e.g. 'The Webfix'.",
                max_length=100,
            ),
        ),
    ]
