# Generated by Django 5.2.8 on 2026-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings_credit_prefix_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About Us"),
                    ("leadership", "Leadership & Board of Directors"),
                    ("products", "Cement & TMT Products"),
                    ("manufacturing_partners", "Manufacturing Partners"),
                    ("distribution_network", "Join Our Dealer Network"),
                    ("star_dealer_program", "Star Dealer Program"),
                    ("star_engineer_program", "Star Engineer Program"),
                    ("star_mason_contractor_scheme", "Star Mason & Contractor Scheme"),
                    ("rewards_recognition", "Rewards & Recognition"),
                    ("quality_assurance", "Quality Assurance"),
                    ("safety_sustainability", "Safety & Sustainability"),
                    ("csr", "Corporate Responsibility (CSR)"),
                    ("roadmap", "Our Growth Roadmap"),
                    ("gallery", "Media Gallery"),
                    ("careers", "Careers at SISTECH"),
                    ("blog", "News & Insights"),
                    ("faq", "Frequently Asked Questions"),
                    ("contact", "Contact Us"),
                    ("privacy_terms", "Privacy Policy & Terms of Use"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
    ]
