# Generated by Django 5.2.8 on 2026-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_page_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_profile",
            field=models.FileField(
                blank=True,
                help_text="Company profile PDF. Shows a Download Company Profile button in the footer.",
                null=True,
                upload_to="site/",
            ),
        ),
    ]
