# Generated by Django 5.2.8 on 2026-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DealerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("business_name", models.CharField(max_length=150)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retailer", "Building material retailer"),
                            ("wholesaler", "Wholesaler / distributor"),
                            ("contractor", "Contractor / builder"),
                            ("new", "Starting a new business"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years_in_business", models.PositiveSmallIntegerField(default=0)),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                (
                    "product_interest",
                    models.CharField(
                        choices=[
                            ("cement", "Cement"),
                            ("tmt", "TMT Bars"),
                            ("both", "Cement and TMT Bars"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "investment_range",
                    models.CharField(
                        choices=[
                            ("under_5", "Below ₹5 lakh"),
                            ("5_10", "₹5–10 lakh"),
                            ("10_25", "₹10–25 lakh"),
                            ("25_plus", "Above ₹25 lakh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_shop", models.BooleanField(default=False)),
                ("has_warehouse", models.BooleanField(default=False)),
                ("existing_brands", models.CharField(blank=True, max_length=250)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("message", models.TextField(blank=True)),
                ("consent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Not approved"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dealer application",
                "verbose_name_plural": "Dealer applications",
                "ordering": ("-created_at",),
            },
        ),
    ]
