# Generated by Django 5.2.8 on 2026-09-28 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerapplication",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_dealer_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="dealerapplication",
            index=models.Index(
                fields=["status", "created_at"], name="network_dea_status_73e500_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealerapplication",
            index=models.Index(fields=["phone"], name="network_dea_phone_bf2a65_idx"),
        ),
    ]
