# Generated by Django 5.2.8 on 2026-09-28 16:32

import apps.careers.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "openings",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("experience_min", models.PositiveSmallIntegerField(default=0)),
                (
                    "experience_max",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Use 0 when there is no upper limit."
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "responsibilities",
                    models.TextField(help_text="Enter one responsibility per line."),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Enter one requirement per line."),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, help_text="Enter one qualification per line."
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, help_text="Comma-separated skills.", max_length=300
                    ),
                ),
                (
                    "salary_display",
                    models.CharField(
                        blank=True,
                        help_text="Optional public salary range.",
                        max_length=100,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job opening",
                "verbose_name_plural": "Job openings",
                "ordering": ("-is_featured", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                (
                    "total_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("current_company", models.CharField(blank=True, max_length=150)),
                ("current_ctc", models.CharField(blank=True, max_length=80)),
                ("expected_ctc", models.CharField(blank=True, max_length=80)),
                ("notice_period", models.CharField(blank=True, max_length=80)),
                (
                    "resume",
                    models.FileField(
                        upload_to="careers/resumes/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "doc", "docx")
                            ),
                            apps.careers.models.validate_resume_size,
                        ],
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("consent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("screening", "Screening"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("selected", "Selected"),
                            ("rejected", "Not selected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="careers.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="careers_job_status_c56afb_idx",
                    ),
                    models.Index(fields=["email"], name="careers_job_email_43f101_idx"),
                ],
            },
        ),
    ]
